app_picture:
    resource: "@AppPictureBundle/Resources/config/routing.yml"
    prefix:   /

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

app_user:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /

