parameters:
#    app_picture.example.class: App\PictureBundle\Example

services:
#    app_picture.example:
#        class: %app_picture.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
